project:
  type: website
  output-dir: C:\Users\pritty01.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "Pritty Arattu's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

